### ISSUE TITLE
SSL/TLS Issues

### ISSUE THREAD

**Issue by iwright-navitend** [johnduprey/CWCAutomateDiagnostics#10]
Getting these:

DIAGNOSTIC-RESPONSE/1
DiagnosticType: Automate
ContentType: json

Exception calling "DownloadString" with "1" argument(s): "The operation has timed out"
!---BEGIN JSON---!
{"version": "Error loading AutomateDiagnostics"}

Or something to the effect of:

The request was aborted: Could not create SSL/TLS secure channel

---

Wondering if instead of all this:

IF([Net.SecurityProtocolType]::Tls) {[Net.ServicePointManager]::SecurityProtocol=[Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls}; IF([Net.SecurityProtocolType]::Tls11) {[Net.ServicePointManager]::SecurityProtocol=[Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls11}; IF([Net.SecurityProtocolType]::Tls12) {[Net.ServicePointManager]::SecurityProtocol=[Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12};

Could be instead of or include somehow this:

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}

Thanks!

**Comment by JohnDuprey** [comment]
I would check the URLs you've specified, ensure that the powershell code is accessible from the agent and that there are no cipher limitations for older operating systems. That check is pretty inclusive, but it's possible the server you're hosting the code from is not.
