### ISSUE TITLE
Low Priority Enhancement: Mac agents can display Location ID: Undefined

### ISSUE THREAD

**Issue by AlexHeylin** [johnduprey/CWCAutomateDiagnostics#11]
No Location ID is in the data in the JSON from the agent because there's no Location ID in the ```/usr/local/ltechagent/state``` file. 
Also worth noting that the Client ID which is in the file and returned JSON can be wrong, thankfully the GUI ignores it anyway. 

![image](https://user-images.githubusercontent.com/270973/162204152-41e0fdfa-799e-47b7-8ca8-6a175d4f5c76.png)

Another one for my list when I get time.  I assume this affects Linux too as ```diag_result``` in ```AutomateDiagnostics.py``` doesn't contain a Location ID field.

**Comment by JohnDuprey** [comment]
There's an updated version of the mac diagnostic using bash instead of python courtesy of @noaht8um. This should hopefully resolve the parsing issues
