### ISSUE TITLE
Server Check for Windows agents

### ISSUE THREAD

**Issue by patbennett** [johnduprey/CWCAutomateDiagnostics#2]
Windows agents are reporting back:  Server Check | ✗ Error \| Server address not matched \| Ping failure \| Version check fail

Mac agents are reporting back: Server Check | ✓ https://labtech.server.com:443

Fresh install of the extension, only changed the LT server address in the configuration

**Comment by JohnDuprey** [comment]
Latest version of the ps1 file corrects this issue
