### ISSUE TITLE
Seeing a lot of the following errors

### ISSUE THREAD

**Issue by ccalverley** [johnduprey/CWCAutomateDiagnostics#4]
DIAGNOSTIC-RESPONSE/1
DiagnosticType: Automate
ContentType: json

The 'var' keyword is not supported in this version of the language.
!---BEGIN JSON---!
{"version": "Error loading AutomateDiagnostics"}

**Comment by JohnDuprey** [comment]
Your agents are probably unable to reach the default location of the script. Your best option would be to point it at your control server.
