### ISSUE TITLE
Control Delayed Until Diagnostics Runs

### ISSUE THREAD

**Issue by xtreme22886** [johnduprey/CWCAutomateDiagnostics#5]
I've just installed and setup this plugin for CW Control and I'm noticing the following behavior. I know that Automate Diagnostics runs when a guest connects. However, this seems to be preventing control of the computer until the Automate Diagnostics finishes it's execution. For example, when I reboot a computer, I use to be able to access it as soon as the guest connected. Now after a reboot, the screen is grey and I cannot do anything with that computer until the Automate Diagnostics finishes. Once it finishes, I can see the remote screen and control the inputs.

My CW Control server is version 19.4.25542.7214 and I have configured Automate Diagnostics to pull the files needed from my Control server and not from GitHub.

Is there something that can be done about this delayed 'access' to the computer after reboots?

**Comment by JohnDuprey** [comment]
This is a downside of diagnosing agents on connect. Set the Maintenance Mode flag to 1 if you don't want that to happen.
