### ISSUE TITLE
Custom Properties need to be adjustable to avoid overwriting existing custom properties.

### ISSUE THREAD

**Issue by matdew** [johnduprey/CWCAutomateDiagnostics#7]

**Comment by willreaves** [comment]
In our Control instance, we have all of the Custom Properties in use, populated by data from our Automate server (GET/POST scripts) and the Control Extension 'Set Session Properties From System Variables'. Some of the data that we are populating overlaps with the data populated by the Automate Diagnostics extension. However, the Custom Properties that were updated don't align, so I ended up with two different properties (four total) displaying the CWA ID and Version number, while losing the data in two of my Custom Properties.

Suggest to provide the ability to change which Custom Properties are used by the Automate Diagnostic extension, or to disable the updating of the Custom Properties entirely. The second option would prevent the automatic session group building from working, so additionally have the option to turn that function off.

**Comment by JohnDuprey** [comment]
Custom property option has been added in the latest release
